# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts

# Copy source and build
COPY tsconfig.json ./
COPY src ./src
RUN npm run build

# Final image
FROM node:lts-alpine
WORKDIR /app

# Copy built files and production deps
COPY package.json package-lock.json ./
RUN npm install --production --ignore-scripts
COPY --from=builder /app/dist ./dist

ENTRYPOINT ["node", "dist/index.js"]
